server:
  error:
    include-stacktrace: ON_TRACE_PARAM

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/security?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: '@#aAndreia32'

 